import 'package:flutter/material.dart';

import '../../core/app_theme.dart';
import '../../services/mongo_service.dart';
import 'admin_announcements_page.dart';
import 'admin_applications_page.dart';
import 'admin_profile_page.dart';

class AdminHomePage extends StatefulWidget { const AdminHomePage({super.key, required this.user}); final Map<String, dynamic> user; @override State<AdminHomePage> createState() => _AdminHomePageState(); }
class _AdminHomePageState extends State<AdminHomePage> { int tab = 0; late final List<Widget> pages; @override void initState() { super.initState(); pages = [_Dashboard(user: widget.user), const AdminApplicationsPage(), const AdminAnnouncementsPage(), AdminProfilePage(user: widget.user)]; } @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: IndexedStack(index: tab, children: pages)), bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (value) => setState(() => tab = value), destinations: const [NavigationDestination(icon: Icon(Icons.grid_view_rounded), label: 'Beranda'), NavigationDestination(icon: Icon(Icons.list_alt), label: 'List Ajuan'), NavigationDestination(icon: Icon(Icons.campaign), label: 'Pengumuman'), NavigationDestination(icon: Icon(Icons.person), label: 'Profil')])); }
class _Dashboard extends StatelessWidget { const _Dashboard({required this.user}); final Map<String, dynamic> user; @override Widget build(BuildContext context) => FutureBuilder<List<Map<String, dynamic>>>(future: MongoService.instance.findAllDeathReports(), builder: (context, snapshot) { final reports = snapshot.data ?? []; int count(String status) => reports.where((report) => report['status']?.toString() == status).length; final totalReports = reports.length; final reSubmitted = reports.where((report) { final status = report['status']?.toString(); return status == 'Diajukan Kembali' || status == 'Menunggu Verifikasi'; }).length; final approved = count('Disetujui'); final rejected = count('Ditolak'); return SingleChildScrollView(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 32), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text('Halo, ${user['name'] ?? 'Admin'}\nSelamat Datang Kembali', style: const TextStyle(fontSize: 18, color: Color(0xFF667085))), const Icon(Icons.notifications, color: alpenBlue)]), const SizedBox(height: 14), const Text('Statistik', style: TextStyle(color: alpenGreen, fontSize: 16)), const SizedBox(height: 10), if (snapshot.connectionState == ConnectionState.waiting) const LinearProgressIndicator() else Wrap(spacing: 12, runSpacing: 12, children: [_Stat('$totalReports', 'Total Pengajuan', alpenBlue, Icons.article_outlined), _Stat('$reSubmitted', 'Menunggu Verifikasi', const Color(0xFFE97520), Icons.watch_later_outlined), _Stat('$approved', 'Pengajuan Disetujui', alpenGreen, Icons.check_circle_outline), _Stat('$rejected', 'Pengajuan Ditolak', const Color(0xFF990000), Icons.cancel_outlined)]), const SizedBox(height: 25), const Text('Pengajuan Terbaru', style: TextStyle(color: alpenGreen, fontSize: 16)), const SizedBox(height: 10), if (reports.isEmpty) const Text('Belum ada pengajuan.') else ...reports.take(5).map((report) => _Recent('${report['reporterName'] ?? '-'}', '${report['status'] ?? 'Pengajuan Baru'}'))])); }); }
class _Stat extends StatelessWidget { const _Stat(this.count, this.label, this.color, this.icon); final String count, label; final Color color; final IconData icon; @override Widget build(BuildContext context) => SizedBox(width: 180, child: Container(height: 124, padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(10)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Icon(icon, color: Colors.white), const SizedBox(width: 9), Text(count, style: const TextStyle(color: Colors.white, fontSize: 34, fontWeight: FontWeight.w800))]), const Spacer(), Text(label, style: const TextStyle(color: Colors.white))]))); }
class _Recent extends StatelessWidget { const _Recent(this.name, this.status); final String name, status; @override Widget build(BuildContext context) => Container(width: double.infinity, margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(12), decoration: BoxDecoration(border: Border.all(color: const Color(0xFFD0D5DD)), borderRadius: BorderRadius.circular(10)), child: Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Chip(label: Text('Pengajuan')), Text(name, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w700))])), Text(status, style: TextStyle(color: status == 'Disetujui' ? alpenGreen : status == 'Ditolak' ? Colors.red : Colors.deepOrange))])); }
